name: Feature Branch Workflow

on:
  push:
    branches:
      - feature/*
  schedule:
    - cron: "45 19 * * 1"
    - cron: "00 00 * * 1"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to production
        if: github.event_name == 'push' && github.ref_type == 'branch'
        run: |
          echo "Deployando para la rama feature/${{ github.event_ref }}"
