name: Release Branch Workflow

on:
  push:
    branches:
      - 'release/*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to production (Release)
        if: github.event_name == 'push' && github.ref_type == 'branch'
        run: |
          echo "Deployando para la rama ${{ github.event_ref }}"
